### ISSUE TITLE
 Error: TypeScript error: f:/downloads/elia_theme-master/src/elia/main.ts(12,23): Error TS2305: Module '"./ts/BrowserView"' has no exported member 'browser'.

### ISSUE THREAD

**Issue by GGM9** [elia-is-me/ELIA_Theme#7]
I got this error on nodejs bash
`[01:41:15] Error: TypeScript error: f:/downloads/elia_theme-master/src/elia/main.ts(12,23): Error TS2305: Module '"./ts/BrowserView"' has no exported member 'browser'.
    at formatError (F:\Downloads\ELIA_Theme-master\node_modules\gulp-cli\lib\versioned\^4.0.0\format-error.js:21:10)
    at Gulp.<anonymous> (F:\Downloads\ELIA_Theme-master\node_modules\gulp-cli\lib\versioned\^4.0.0\log\events.js:33:15)
    at Gulp.emit (events.js:412:35)
    at Gulp.emit (domain.js:470:12)
    at Object.error (F:\Downloads\ELIA_Theme-master\node_modules\undertaker\lib\helpers\createExtensions.js:61:10)
    at handler (F:\Downloads\ELIA_Theme-master\node_modules\now-and-later\lib\map.js:50:14)
    at f (F:\Downloads\ELIA_Theme-master\node_modules\once\once.js:25:25)
    at f (F:\Downloads\ELIA_Theme-master\node_modules\once\once.js:25:25)
    at tryCatch (F:\Downloads\ELIA_Theme-master\node_modules\async-done\index.js:24:15)
    at done (F:\Downloads\ELIA_Theme-master\node_modules\async-done\index.js:40:12)` 
    How should I fix this?

**Comment by elia-is-me** [comment]
sorry it's not available now because days ago i push and broke my code...
i'm trying to fix it and may be some days later.
